Update deploy-getuser.yml

diff --git a/.github/workflows/deploy-getuser.yml b/.github/workflows/deploy-getuser.yml
--- a/.github/workflows/deploy-getuser.yml
+++ b/.github/workflows/deploy-getuser.yml
@@ -74,10 +74,10 @@ jobs:
             docker rmi alevm98/getuserservice:latest || echo "No había imagen previa para eliminar"
 
             echo "📥 Descargando nueva imagen desde Docker Hub..."
-            docker pull fernanyag20/validateuserservice:latest || { echo "🚨 Error al hacer pull de la imagen"; exit 1; }
+            docker pull fernanyag20/getuserservice:latest || { echo "🚨 Error al hacer pull de la imagen"; exit 1; }
 
             echo "🚀 Iniciando nuevo contenedor..."
-            docker run -d --restart unless-stopped --name validateuserservice -p 80:80 fernanyag20/validateuserservice:latest
+            docker run -d --restart unless-stopped --name getuserservice -p 80:80 fernanyag20/getuserservice:latestt
 
             echo "🔍 Verificando contenedores activos..."
             docker ps -a
